stages:
  - pages
  - push

  - retrieve-dependencies
  - build
  - setup
  - sign
  - release
  - push-packages



include:

  # Retrieve dependencies
  # Stage: retrieve-dependencies
  - local: .gitlab-ci/get-caen-lib-windows.yml

  # Build Jobs
  # Stage: build
  - local: .gitlab-ci/build-jobs.yml

  # Build and digitally sign Windows setup
  # Stages: setup, sign
  - local: .gitlab-ci/build-sign-setup.yml

  # Perform several nirelease pushes
  # Stage: release
  - local: .gitlab-ci/ni-releases.yml

  # Push packages Jobs
  # Stage: push-packages
  - local: .gitlab-ci/push-packages.yml
      


pages:
  stage: pages
  image: harbor.nuclearinstruments.eu/library/doxygen:1
  tags:
    - docker-linux
    - light

  script:
    - doxygen
    - mkdir -p public
    - mv docs/html/* public/

    # Zip for setup status
    - cp -r public scisdk_docs
    - zip -r scisdk_docs.zip scisdk_docs

  when: always
  artifacts:
    paths:
      # Include public for page deployment
      - public
      - scisdk_docs.zip


push_github:
  stage: push
  image: harbor.nuclearinstruments.eu/nibuntu/services-22.04:2
  tags:
    - docker-linux
    - light

  script:
    - git config --global --add safe.directory '*'
    - git config remote.github_cicd.url >&- || git remote add github_cicd https://NuclearInstruments:${GITHUB_TOKEN}@github.com/NuclearInstruments/SCISDK.git
    - git push -u github_cicd HEAD:master --force

