var searchData=
[
  ['fft_20power_20spectrum_20driver_0',['FFT (Power Spectrum) driver',['../md_docs_2fft.html',1,'']]],
  ['fft_2emd_1',['fft.md',['../fft_8md.html',1,'']]],
  ['file_2',['file',['../md_docs_2fft.html#autotoc_md230',1,'Processing decoded data and store in a file'],['../md_docs_2fft.html#autotoc_md231',1,'Processing raw data and store in a file'],['../md_docs_2digitizer.html#autotoc_md107',1,'Read raw data and write on file'],['../md_docs_2registers-file.html',1,'Register File']]],
  ['file_20on_20channel_20per_20column_3',['Read decoded data and write on file, on channel per column',['../md_docs_2digitizer.html#autotoc_md106',1,'']]],
  ['file_20one_20channel_20per_20column_4',['file one channel per column',['../md_docs_2oscilloscope.html#autotoc_md84',1,'Processing decoded data and store in a file, one channel per column'],['../md_docs_2oscilloscope.html#autotoc_md83',1,'Processing decoded data and store in a file, one channel per column']]],
  ['file_20structure_5',['File structure',['../index.html#autotoc_md6',1,'']]],
  ['fine_6',['fine',['../struct_s_c_i_s_d_k___p_e_t_i_r_o_c___p_i_x_e_l.html#a8ffc3df2feb025799c5ab5625f6c0939',1,'SCISDK_PETIROC_PIXEL']]],
  ['fine_5ftimestamp_7',['fine_timestamp',['../struct_s_c_i_s_d_k___f_e___o_p_e_n_d_p_p___e_v_e_n_t.html#a548f3e7f39d6041af358ffbeb4acd664',1,'SCISDK_FE_OPENDPP_EVENT']]],
  ['flags_8',['flags',['../struct_s_c_i_s_d_k___p_e_t_i_r_o_c___p_a_c_k_e_t.html#accc031846ac7b4e56d12165232f6b496',1,'SCISDK_PETIROC_PACKET::flags'],['../struct_s_c_i_s_d_k___c_i_t_i_r_o_c___p_a_c_k_e_t.html#a168453b7504e039f1a4863fc03612410',1,'SCISDK_CITIROC_PACKET::flags']]],
  ['flags_5fa_9',['flags_a',['../struct_s_c_i_s_d_k___f_e___o_p_e_n_d_p_p___e_v_e_n_t.html#a5cd57e294188b5e7fc819450022427cd',1,'SCISDK_FE_OPENDPP_EVENT']]],
  ['flags_5fb_10',['flags_b',['../struct_s_c_i_s_d_k___f_e___o_p_e_n_d_p_p___e_v_e_n_t.html#a0735fd381d74266b5a08dbb247ed6023',1,'SCISDK_FE_OPENDPP_EVENT']]],
  ['flight_20spectrum_11',['Time of Flight Spectrum',['../md_docs_2tof-spectrum.html',1,'']]],
  ['flush_12',['flush',['../struct_s_c_i_s_d_k___f_e___o_p_e_n_d_p_p___e_v_e_n_t.html#ac25e44a817b8dfa141ce5823908647bc',1,'SCISDK_FE_OPENDPP_EVENT']]],
  ['for_20linux_13',['6.2. Compiling for Linux',['../index.html#autotoc_md11',1,'']]],
  ['for_20readout_14',['8.6 Allocate buffers for readout',['../index.html#autotoc_md27',1,'']]],
  ['for_20windows_15',['6.1. Compiling for Windows',['../index.html#autotoc_md10',1,'']]],
  ['format_16',['format',['../md_docs_2custompacket.html#autotoc_md119',1,'Output data Format'],['../md_docs_2fft.html#autotoc_md217',1,'Output data Format'],['../md_docs_2spectrum.html#autotoc_md143',1,'Output data Format'],['../md_docs_22dhistogram.html#autotoc_md164',1,'Output data Format'],['../md_docs_2tof-spectrum.html#autotoc_md176',1,'Output data Format'],['../md_docs_2list.html#autotoc_md197',1,'Output data Format'],['../md_docs_2rate-meter.html#autotoc_md260',1,'Output data Format'],['../md_docs_2frame.html#autotoc_md239',1,'Output data Format'],['../md_docs_2digitizer.html#autotoc_md96',1,'Output data Format'],['../md_docs_2oscilloscope.html#autotoc_md68',1,'Output data Format']]],
  ['formware_17',['Raw data formware',['../md_docs_2oscilloscope-dual.html#autotoc_md87',1,'']]],
  ['frame_20imaging_20driver_18',['Frame (imaging) driver',['../md_docs_2frame.html',1,'']]],
  ['frame_20transfer_20driver_19',['frame transfer driver',['../md_docs_2citiroc-frame.html',1,'Citiroc Frame transfer driver'],['../md_docs_2petiroc-frame.html',1,'Petiroc Frame Transfer driver']]],
  ['frame_2emd_20',['frame.md',['../frame_8md.html',1,'']]],
  ['from_20a_20board_21',['from a board',['../index.html#autotoc_md28',1,'8.7 Readout data from a board'],['../index.html#autotoc_md37',1,'9.8 Readout data from a board']]],
  ['from_20binary_20package_22',['from binary package',['../index.html#autotoc_md7',1,'4. Windows: Installation from binary package'],['../index.html#autotoc_md8',1,'5. Linux: Installation from binary package']]],
  ['from_20source_23',['6. Compiling from source',['../index.html#autotoc_md9',1,'']]],
  ['ftdi_24',['INSTALL FTDI',['../index.html#autotoc_md14',1,'']]],
  ['functions_3a_25',['Supported functions:',['../md_docs_2boardendpoint.html#autotoc_md275',1,'']]]
];
