var searchData=
[
  ['a_20board_0',['a board',['../index.html#autotoc_md25',1,'8.4 Connecting to a board'],['../index.html#autotoc_md28',1,'8.7 Readout data from a board'],['../index.html#autotoc_md37',1,'9.8 Readout data from a board']]],
  ['a_20custom_20application_1',['CREATE A CUSTOM APPLICATION',['../index.html#autotoc_md17',1,'']]],
  ['a_20file_2',['a file',['../md_docs_2fft.html#autotoc_md230',1,'Processing decoded data and store in a file'],['../md_docs_2fft.html#autotoc_md231',1,'Processing raw data and store in a file']]],
  ['a_20file_20one_20channel_20per_20column_3',['a file one channel per column',['../md_docs_2oscilloscope.html#autotoc_md83',1,'Processing decoded data and store in a file, one channel per column'],['../md_docs_2oscilloscope.html#autotoc_md84',1,'Processing decoded data and store in a file, one channel per column']]],
  ['a_20maven_20managed_20project_4',['8.2 Include in a Maven managed project',['../index.html#autotoc_md23',1,'']]],
  ['a_20register_20value_5',['a register value',['../index.html#autotoc_md26',1,'8.5 Set/Get a register value'],['../index.html#autotoc_md35',1,'9.6 Get a register value'],['../index.html#autotoc_md36',1,'9.7 Set a register value']]],
  ['a_20single_20channels_6',['a single channels',['../md_docs_2boards_2x5560se.html#autotoc_md300',1,'Configure a single channels'],['../md_docs_2boards_2dt5771.html#autotoc_md310',1,'Configure a single channels']]],
  ['access_20to_20board_20endpoints_7',['access to board endpoints',['../md_docs_2boards_2opendpp.html#autotoc_md278',1,'Access to board endpoints'],['../md_docs_2boards_2openscope.html#autotoc_md284',1,'Access to board endpoints']]],
  ['acquisition_20length_8',['acquisition length',['../md_docs_2digitizer.html#autotoc_md90',1,'Acquisition length'],['../md_docs_2list.html#autotoc_md191',1,'Acquisition length'],['../md_docs_2custompacket.html#autotoc_md110',1,'Acquisition length']]],
  ['acquisition_20modes_9',['acquisition modes',['../md_docs_2oscilloscope.html#autotoc_md63',1,'Acquisition Modes'],['../md_docs_2fft.html#autotoc_md213',1,'Acquisition Modes']]],
  ['add_20them_20to_20labview_20palette_10',['9.3 Use SciSDK VIs without add them to LabView Palette',['../index.html#autotoc_md32',1,'']]],
  ['add_20vis_20to_20palette_11',['9.2 Manually add VIs to palette',['../index.html#autotoc_md31',1,'']]],
  ['additional_20examples_12',['additional examples',['../md_docs_2fft.html#autotoc_md228',1,'Additional Examples'],['../md_docs_2digitizer.html#autotoc_md105',1,'Additional Examples'],['../md_docs_2custompacket.html#autotoc_md131',1,'Additional Examples'],['../md_docs_2spectrum.html#autotoc_md154',1,'Additional Examples'],['../md_docs_2tof-spectrum.html#autotoc_md187',1,'Additional Examples'],['../md_docs_2list.html#autotoc_md207',1,'Additional Examples'],['../md_docs_2frame.html#autotoc_md253',1,'Additional Examples'],['../md_docs_2oscilloscope.html#autotoc_md79',1,'Additional Examples']]],
  ['aggregate_5fcounter_13',['aggregate_counter',['../struct_s_c_i_s_d_k___f_e___o_p_e_n_d_p_p___e_v_e_n_t.html#acffc6b2fd3d0e42fa1734e6bb38490a2',1,'SCISDK_FE_OPENDPP_EVENT']]],
  ['all_20channels_20of_20the_20board_14',['Configure all channels of the board',['../md_docs_2boards_2x5560se.html#autotoc_md303',1,'']]],
  ['allignment_20check_15',['Allignment check',['../md_docs_2custompacket.html#autotoc_md114',1,'']]],
  ['allocate_20buffers_20for_20readout_16',['8.6 Allocate buffers for readout',['../index.html#autotoc_md27',1,'']]],
  ['allocated_5fbins_17',['allocated_bins',['../struct_s_c_i_s_d_k___e_m_u_l_a_t_o_r___e_n_e_r_g_y___s_p_e_c_t_r_u_m.html#a337dfd2268d8754eb82e84a941d9a50a',1,'SCISDK_EMULATOR_ENERGY_SPECTRUM']]],
  ['allocation_18',['allocation',['../md_docs_2list.html#autotoc_md196',1,'Buffer Allocation'],['../md_docs_2digitizer.html#autotoc_md95',1,'Buffer Allocation'],['../md_docs_2frame.html#autotoc_md238',1,'Buffer Allocation'],['../md_docs_2custompacket.html#autotoc_md118',1,'Buffer Allocation']]],
  ['an_20ant_20managed_20project_19',['8.1 Include in an Ant managed project',['../index.html#autotoc_md22',1,'']]],
  ['analog_20',['analog',['../struct_s_c_i_s_d_k___o_s_c_i_l_l_o_s_c_o_p_e___d_u_a_l___d_e_c_o_d_e_d___b_u_f_f_e_r.html#a83f3cb8144b738fdefcbc7b08e4f51f6',1,'SCISDK_OSCILLOSCOPE_DUAL_DECODED_BUFFER::analog'],['../struct_s_c_i_s_d_k___d_i_g_i_t_i_z_e_r___d_e_c_o_d_e_d___b_u_f_f_e_r.html#aab2723dc65566d7499fc48d2b6d1091b',1,'SCISDK_DIGITIZER_DECODED_BUFFER::analog'],['../struct_s_c_i_s_d_k___o_s_c_i_l_l_o_s_c_o_p_e___d_e_c_o_d_e_d___b_u_f_f_e_r.html#a58d35a4c3e9eaa19d737705e3a508e47',1,'SCISDK_OSCILLOSCOPE_DECODED_BUFFER::analog']]],
  ['analog_20node_21',['analog node',['../md_docs_2boards_2dt1260.html#autotoc_md290',1,'How to use the boardapi/analog node'],['../md_docs_2boards_2x5560se.html#autotoc_md297',1,'How to use the boardapi/analog node'],['../md_docs_2boards_2dt5771.html#autotoc_md307',1,'How to use the boardapi/analog node']]],
  ['analog_20signal_22',['Trigger on analog signal',['../md_docs_2oscilloscope.html#autotoc_md81',1,'']]],
  ['and_20install_20the_20dt1260_20libraries_20and_20scisdk_20on_20ubuntu_23',['6.2.1 Example: how to compile and install the DT1260 libraries and SciSDK on Ubuntu',['../index.html#autotoc_md12',1,'']]],
  ['and_20max_24',['Min and Max',['../md_docs_2spectrum.html#autotoc_md138',1,'']]],
  ['and_20print_20decoded_20data_25',['C read and print decoded data',['../md_docs_2frame.html#autotoc_md254',1,'']]],
  ['and_20progress_26',['Limit and progress',['../md_docs_2spectrum.html#autotoc_md156',1,'']]],
  ['and_20store_20in_20a_20file_27',['and store in a file',['../md_docs_2fft.html#autotoc_md230',1,'Processing decoded data and store in a file'],['../md_docs_2fft.html#autotoc_md231',1,'Processing raw data and store in a file']]],
  ['and_20store_20in_20a_20file_20one_20channel_20per_20column_28',['and store in a file one channel per column',['../md_docs_2oscilloscope.html#autotoc_md83',1,'Processing decoded data and store in a file, one channel per column'],['../md_docs_2oscilloscope.html#autotoc_md84',1,'Processing decoded data and store in a file, one channel per column']]],
  ['and_20than_20open_20it_20in_20python_20and_20decode_20it_29',['Dump raw data in C and than open it in python and decode it',['../md_docs_2custompacket.html#autotoc_md134',1,'']]],
  ['and_20write_20on_20file_30',['Read raw data and write on file',['../md_docs_2digitizer.html#autotoc_md107',1,'']]],
  ['and_20write_20on_20file_20on_20channel_20per_20column_31',['Read decoded data and write on file, on channel per column',['../md_docs_2digitizer.html#autotoc_md106',1,'']]],
  ['ant_20managed_20project_32',['8.1 Include in an Ant managed project',['../index.html#autotoc_md22',1,'']]],
  ['application_33',['CREATE A CUSTOM APPLICATION',['../index.html#autotoc_md17',1,'']]],
  ['applying_20the_20configuration_34',['applying the configuration',['../md_docs_2boards_2x5560se.html#autotoc_md298',1,'Applying the configuration'],['../md_docs_2boards_2dt5771.html#autotoc_md308',1,'Applying the configuration']]],
  ['arm_35',['arm',['../md_docs_2fft.html#autotoc_md214',1,'Auto Arm'],['../md_docs_2oscilloscope.html#autotoc_md65',1,'Auto Arm']]],
  ['armed_36',['armed',['../struct_s_c_i_s_d_k___f_f_t___s_t_a_t_u_s.html#a015a9d5d25c3c04f51ed052eb278dfc5',1,'SCISDK_FFT_STATUS::armed'],['../struct_s_c_i_s_d_k___o_s_c_i_l_l_o_s_c_o_p_e___s_t_a_t_u_s.html#a3eb638c5ff2ae5c5356b5bba69103436',1,'SCISDK_OSCILLOSCOPE_STATUS::armed']]],
  ['asic_37',['asic',['../struct_s_c_i_s_d_k___c_i_t_i_r_o_c___p_a_c_k_e_t.html#ac57593ffdb596cf676b5ad4865241427',1,'SCISDK_CITIROC_PACKET::asic'],['../struct_s_c_i_s_d_k___p_e_t_i_r_o_c___p_a_c_k_e_t.html#a179f8e3ce47277decd041aef69d7705c',1,'SCISDK_PETIROC_PACKET::asic']]],
  ['auto_20arm_38',['auto arm',['../md_docs_2fft.html#autotoc_md214',1,'Auto Arm'],['../md_docs_2oscilloscope.html#autotoc_md65',1,'Auto Arm']]],
  ['automatically_20with_20scisdk_20setup_39',['9.1 Install automatically with SciSDK setup',['../index.html#autotoc_md30',1,'']]]
];
