# Build and digitally sign Windows setup

build_setup:
  stage: setup
  image: harbor.nuclearinstruments.eu/windows/innosetup:1
  tags:
    - docker-windows
  dependencies: 
    - build_vs2022_windows
    - pages
    - run-get-lib-windows
    - nirelease-pull
  
  script:
    - .\build_setup.ps1 $CI_COMMIT_TAG
  artifacts:
    paths:
      - output/*.exe    
  rules:
    - if: $CI_COMMIT_TAG


digital_signature:
  stage: sign
  tags:
    - windows-signature
  dependencies: 
    - build_setup  

  script:
    - sign_executable.cmd "output/SciSDKSetup.exe"

  artifacts:
    paths:
      - output/SciSDKSetup.exe
  rules:
    - if: $CI_COMMIT_TAG

