# This yml file contains all the CICD Jobs in charge of pushing binaries to package registries

spec:
  inputs:
    # --- Required ---


    # --- Optional ---

    # Job Stages
    stage:
      type: string
      description: "Stage name for the package jobs"
      default: push-packages


---


include:
  - component: $CI_SERVER_FQDN/cicd-catalogs/build-catalogs/nibuntu/nibuntu-all-arch@~latest
    inputs:
      job_name: deb_push
      stage: $[[ inputs.stage ]]
      runner_tags:
        - docker-linux
        - light
      dependencies: 
        # MUST match name in .gitlab-ci/build-jobs.yml. Cannot do with VARIABLES
        - build_ubuntu_all_arch

      script:
        # Debug print
        - ls -l
        - ls -l debs/

        - echo "Publishing for release  $LINUXRELEASE" 
        - scripts/push_packages.sh

      rules: 
        - if: $CI_COMMIT_TAG



