# This yml file contains the CICD Job to retrieve CAEN libraries for Windows

spec:
  inputs:
    # --- Required ---


    # --- Optional ---

    # Job Stages
    stage:
      type: string
      description: "Stage name for the jobs"
      default: retrieve-dependencies


---


# Perform all the pulls of nirelease artifacts
nirelease-pull:
  stage: $[[ inputs.stage ]]
  image: harbor.nuclearinstruments.eu/apps/release-manager:2
  tags:
    - docker-linux
    - light

  script:
    - nirelease --pull -u DT1260/rev-A/release/sw-lib/DT1260SDK/ -o tmp
    - nirelease --pull -u X5560/rev-B/release/sw-lib/X5560SDK/ -o tmp
    - nirelease --pull -u DT5771/rev-A/release/sw-lib/dt5771sdk-windows/ -o tmp

  artifacts:
    paths:
      - tmp/
  rules: 
    - if: $CI_COMMIT_TAG



run-get-lib-windows:
  stage: $[[ inputs.stage ]]
  image: harbor.nuclearinstruments.eu/microsoft/windows/servercore:ltsc2022
  tags:
    - windows

  script:
    # Create directories for artifacts
    - New-Item -ItemType Directory -Path "artifacts\caenlib\bin\x86" -Force
    - New-Item -ItemType Directory -Path "artifacts\caenlib\bin\x86_64" -Force
    - New-Item -ItemType Directory -Path "artifacts\caenlib\include" -Force
    - New-Item -ItemType Directory -Path "artifacts\caenlib\lib\x86" -Force
    - New-Item -ItemType Directory -Path "artifacts\caenlib\lib\x86_64" -Force
    # Get dependencies
    - '[System.Net.WebRequest]::DefaultWebProxy = [System.Net.WebRequest]::GetSystemWebProxy()'
    - '[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials'
    # - CAEN FELib
    - Invoke-WebRequest "https://caen.it/wp-json/caen/v1/download-file?file_id=10690" -Headers @{"Authorization"="Bearer ${CAEN_WEBSITE_API_BEARER}"} -OutFile artifacts_fe.zip -UserAgent "curl/7.83.1"
    - Expand-Archive -Path artifacts_fe.zip -DestinationPath .
    - 'Start-Process -FilePath ".\CAEN FELib*.exe" -ArgumentList "/VERYSILENT /NORESTART /NOICONS /COMPONENTS=`"dll,lib`"" -Wait'
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN FELib\bin\x86\*.dll" -Destination "artifacts\caenlib\bin\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN FELib\bin\x86_64\*.dll" -Destination "artifacts\caenlib\bin\x86_64\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN FELib\include\*" -Destination "artifacts\caenlib\include\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN FELib\lib\x86\*.lib" -Destination "artifacts\caenlib\lib\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN FELib\lib\x86_64\*.lib" -Destination "artifacts\caenlib\lib\x86_64\" -Recurse -Force
    # - CAEN Dig2
    - Invoke-WebRequest "https://caen.it/wp-json/caen/v1/download-file?file_id=10833" -Headers @{"Authorization"="Bearer ${CAEN_WEBSITE_API_BEARER}"} -OutFile artifacts_dig2.zip -UserAgent "curl/7.83.1"
    - Expand-Archive -Path artifacts_dig2.zip -DestinationPath .
    - 'Start-Process -FilePath ".\CAEN Dig2*.exe" -ArgumentList "/VERYSILENT /NORESTART /NOICONS /COMPONENTS=`"dll`"" -Wait'
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN Dig2\bin\x86\*.dll" -Destination "artifacts\caenlib\bin\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\Digitizers\CAEN Dig2\bin\x86_64\*.dll" -Destination "artifacts\caenlib\bin\x86_64\" -Recurse -Force
    # - CAEN VME
    - Invoke-WebRequest "https://caen.it/wp-json/caen/v1/download-file?file_id=8635" -Headers @{"Authorization"="Bearer ${CAEN_WEBSITE_API_BEARER}"} -OutFile artifacts_vme.zip -UserAgent "curl/7.83.1"
    - Expand-Archive -Path artifacts_vme.zip -DestinationPath .
    - 'Start-Process -FilePath ".\CAENVMELib*.exe" -ArgumentList "/VERYSILENT /NORESTART /NOICONS /COMPONENTS=`"program,libs`"" -Wait'
    - Copy-Item -Path "C:\Program Files\CAEN\VME\lib\x86\*.dll" -Destination "artifacts\caenlib\bin\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\VME\lib\x86_64\*.dll" -Destination "artifacts\caenlib\bin\x86_64\" -Recurse -Force
    # - CAEN Comm
    - Invoke-WebRequest "https://caen.it/wp-json/caen/v1/download-file?file_id=8294" -Headers @{"Authorization"="Bearer ${CAEN_WEBSITE_API_BEARER}"} -OutFile artifacts_comm.zip -UserAgent "curl/7.83.1"
    - Expand-Archive -Path artifacts_comm.zip -DestinationPath .
    - 'Start-Process -FilePath ".\CAENComm*.exe" -ArgumentList "/VERYSILENT /NORESTART /NOICONS /COMPONENTS=`"program,libs`"" -Wait'
    - Copy-Item -Path "C:\Program Files\CAEN\Comm\lib\x86\*.dll" -Destination "artifacts\caenlib\bin\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\Comm\lib\x86_64\*.dll" -Destination "artifacts\caenlib\bin\x86_64\" -Recurse -Force
    # - CAEN PLU
    - Invoke-WebRequest "https://caen.it/wp-json/caen/v1/download-file?file_id=10100" -Headers @{"Authorization"="Bearer ${CAEN_WEBSITE_API_BEARER}"} -OutFile artifacts_plu.zip -UserAgent "curl/7.83.1"
    - Expand-Archive -Path artifacts_plu.zip -DestinationPath .
    - 'Start-Process -FilePath ".\CAENPLU*.exe" -ArgumentList "/VERYSILENT /NORESTART /NOICONS /COMPONENTS=`"program,libs`"" -Wait'
    - Copy-Item -Path "C:\Program Files\CAEN\PLULibrary\lib\x86\*.dll" -Destination "artifacts\caenlib\bin\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\PLULibrary\lib\x86_64\*.dll" -Destination "artifacts\caenlib\bin\x86_64\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\PLULibrary\include\*" -Destination "artifacts\caenlib\include\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\PLULibrary\lib\x86\*.lib" -Destination "artifacts\caenlib\lib\x86\" -Recurse -Force
    - Copy-Item -Path "C:\Program Files\CAEN\PLULibrary\lib\x86_64\*.lib" -Destination "artifacts\caenlib\lib\x86_64\" -Recurse -Force

  artifacts:
    paths:
      - artifacts/
  rules: 
    - if: $CI_COMMIT_TAG



